# Generated by Django 3.0.5 on 2020-04-24 03:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('dishName', models.TextField()),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Menu')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('minOptions', models.IntegerField()),
                ('maxOptions', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuOptionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calories', models.IntegerField()),
                ('minOptions', models.IntegerField()),
                ('maxOptions', models.IntegerField()),
                ('menuOptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.MenuOptions')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.MenuGroup'),
        ),
        migrations.CreateModel(
            name='RestaurantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('address_1', models.CharField(max_length=254)),
                ('address_2', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('province', models.CharField(choices=[('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NB', 'Nova Scotia'), ('NS', 'New Brunswick'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=254)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='[A-Za-z]\\d[A-Za-z]\\d[A-Za-z]\\d')])),
                ('country', models.CharField(choices=[('CAN', 'Canada')], default='CAN', max_length=6)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Restaurant')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'abstract': False,
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
        migrations.AddConstraint(
            model_name='menuoptions',
            constraint=models.CheckConstraint(check=models.Q(minOptions__lte=django.db.models.expressions.F('maxOptions')), name='optionConstraint'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('weekday', 'from_hour', 'to_hour')},
        ),
    ]
