# Generated by Django 3.0.5 on 2020-04-26 03:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skip_id', models.CharField(max_length=36, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Menu')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('calories', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.MenuGroups')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('short_name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_1', models.CharField(max_length=254)),
                ('address_2', models.CharField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=254)),
                ('province', models.CharField(choices=[('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NB', 'Nova Scotia'), ('NS', 'New Brunswick'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=254)),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='[A-Za-z]\\d[A-Za-z]\\s\\d[A-Za-z]\\d')])),
                ('country', models.CharField(choices=[('CAN', 'Canada')], default='CAN', max_length=6)),
                ('is_open', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='menus.Menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='menus.Restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantLocationAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('startHour', models.IntegerField()),
                ('startMinute', models.IntegerField()),
                ('endHour', models.IntegerField()),
                ('endMinute', models.IntegerField()),
                ('restaurant_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.RestaurantLocation')),
            ],
            options={
                'ordering': ('weekday', 'startHour', 'startMinute'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.MenuItems')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuOptionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.TextField()),
                ('price', models.IntegerField()),
                ('calories', models.IntegerField(null=True)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.MenuOptions')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuGroupAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('startHour', models.IntegerField()),
                ('startMinute', models.IntegerField()),
                ('endHour', models.IntegerField()),
                ('endMinute', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.MenuGroups')),
            ],
            options={
                'ordering': ('weekday', 'startHour', 'startMinute'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='menuoptions',
            constraint=models.CheckConstraint(check=models.Q(minimum__lte=django.db.models.expressions.F('maximum')), name='optionConstraint'),
        ),
        migrations.AddConstraint(
            model_name='menuoptionchoices',
            constraint=models.CheckConstraint(check=models.Q(minimum__lte=django.db.models.expressions.F('maximum')), name='choiceConstraint'),
        ),
    ]
